### ISSUE TITLE
bug: Doesn't work, some nui error

### ISSUE THREAD

**Issue by daUnknownCoder** [SuperBo/fugit2.nvim#10]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

6.7.9-arch1-1

### Describe the bug

I cannot start the plugin:
Using lazy, config:
```lua
  {
    "SuperBo/fugit2.nvim",
    lazy = true,
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-tree/nvim-web-devicons",
      "nvim-lua/plenary.nvim",
      {
        "chrisgrieser/nvim-tinygit",
        dependencies = { "stevearc/dressing.nvim" },
      },
    },
    cmd = { "Fugit2", "Fugit2Graph" },
    keys = {
      { "<leader>F", mode = "n", "<cmd>Fugit2<cr>" },
    },
  },
```

the error I get:
```lua
Error executing Lua callback: ...cal/share/NeutronVim/lazy/nui.nvim/lua/nui/text/init.lua:73: Invalid 'ns_id': 0
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...cal/share/NeutronVim/lazy/nui.nvim/lua/nui/text/init.lua:73: in function 'highlight'
	...cal/share/NeutronVim/lazy/nui.nvim/lua/nui/line/init.lua:58: in function 'highlight'
	...cal/share/NeutronVim/lazy/nui.nvim/lua/nui/line/init.lua:73: in function 'render'
	...im/lazy/fugit2.nvim/lua/fugit2/view/components/menus.lua:98: in function 'set_text'
	...im/lazy/fugit2.nvim/lua/fugit2/view/components/menus.lua:53: in function 'init'
	...l/share/NeutronVim/lazy/nui.nvim/lua/nui/object/init.lua:132: in function 'Confirm'
	...utronVim/lazy/fugit2.nvim/lua/fugit2/view/git_status.lua:236: in function 'init'
	...l/share/NeutronVim/lazy/nui.nvim/lua/nui/object/init.lua:132: in function 'GitStatus'
	...share/NeutronVim/lazy/fugit2.nvim/lua/fugit2/view/ui.lua:24: in function 'new_fugit2_status_window'
	...al/share/NeutronVim/lazy/fugit2.nvim/lua/fugit2/init.lua:64: in function <...al/share/NeutronVim/lazy/fugit2.nvim/lua/fugit2/init.lua:61>
```

### Steps To Reproduce

Just try using: `"Fugit2"`, `"Fugit2Graph"`, `"Fugit2Diff"`

### Expected Behavior

It should work obv

**Comment by ceuk** [comment]
@daUnknownCoder did you already have [nui.nvim](https://github.com/MunifTanjim/nui.nvim) installed? You could try update it maybe

**Comment by ceuk** [comment]
Ah, try remove `lazy = true` from your plugin setup

**Comment by ceuk** [comment]
Also add `opts = {}` - I'm not sure if lazy calls `.setup` without that line, which would explain why the namespace is still `0`

**Comment by ceuk** [comment]
@daUnknownCoder try adding `opts = {}` to your lazy config. I'm not sure if lazy calls `.setup` without that line, which would explain why the namespace is still 0

**Comment by daUnknownCoder** [comment]
current setup:
```lua
  {
    "SuperBo/fugit2.nvim",
    lazy = false,
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-tree/nvim-web-devicons",
      "nvim-lua/plenary.nvim",
      {
        "chrisgrieser/nvim-tinygit",
        dependencies = { "stevearc/dressing.nvim" },
      },
    },
    cmd = { "Fugit2", "Fugit2Graph" },
    keys = {
      { "<leader>F", mode = "n", "<cmd>Fugit2<cr>" },
    },
  },
``` gg

still not working

**Comment by daUnknownCoder** [comment]
yeah works with `opts={}`, why didnt it work b4?

**Comment by SuperBo** [comment]
@daUnknownCoder , or you can set config = true. This is related to plugin init process (in which I setup some highlight group for better coloring).

<img width="889" alt="Screenshot 2024-03-21 at 20 32 18" src="https://github.com/SuperBo/fugit2.nvim/assets/2666479/a11be16a-90c7-449e-be7c-1d9adde0fa83">
