### ISSUE TITLE
feature: Open status window with patch view enabled

### ISSUE THREAD

**Issue by rpbaptist** [SuperBo/fugit2.nvim#102]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

When opening the git status window I always immediately press `=` because I find it more helpful to see the diff.

### Describe the solution you'd like

Save me a step and allow the config to open status view with patch view enabled.

### Describe alternatives you've considered

Perhaps an autocommand tied to opening the window?

**Comment by SuperBo** [comment]
Hi @rpbaptist, thank you for using Fugit2. I have a vacation in next week. I will add this feature when I'm back from vacation. :D

**Comment by rpbaptist** [comment]
Amazing! Enjoy your holiday!

**Comment by SuperBo** [comment]
Hi @rpbaptist, I add one commit to allow you show patch on startup. https://github.com/SuperBo/fugit2.nvim/pull/106

Please set `show_path = true` in your config and test it

**Comment by rpbaptist** [comment]
Working splendidly! Thank you!

**Comment by SuperBo** [comment]
@rpbaptist, quick fix already deployed. https://github.com/SuperBo/fugit2.nvim/pull/108

Sorry for this error :D

**Comment by rpbaptist** [comment]
Thank you again!
