### ISSUE TITLE
feature: Opening fugit inside Oil.nvim window

### ISSUE THREAD

**Issue by damian-elenbaas** [SuperBo/fugit2.nvim#103]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

I'm currently using Oil.nvim as file explorer. In this explorer when i'm in a folder, i can't open the Fugit window. This is because the path that Fugit receives starts with the oil prefix like this: `oil:///{full path to folder}`. 

Error message:
![image](https://github.com/user-attachments/assets/a3292462-ecad-47e4-afa9-58a31be2c9a4)

### Describe the solution you'd like

I would like to be able to open Fugit inside the Oil.nvim file explorer. 

How i would implement this, is trying to check if a prefix like that from oil sits at the start of the received path. If a prefix exists, it should be removed. Then you will have a correct path to open.

### Describe alternatives you've considered

Described above.

**Comment by SuperBo** [comment]
Roger @damian-elenbaas, Are you using Oil on Windows?

**Comment by SuperBo** [comment]
Hi @damian-elenbaas, already merged changes https://github.com/SuperBo/fugit2.nvim/pull/107 to support oil.nvim.

Futhermore, you can use this recipe for better integration.
https://github.com/SuperBo/fugit2.nvim/wiki/Integrations#oilnvim

**Comment by damian-elenbaas** [comment]
Hi @SuperBo, im using Windows yes. I will check in out when i have time 👍

**Comment by damian-elenbaas** [comment]
The vim.cmd part of the instructuctions doesnt work:

![image](https://github.com/user-attachments/assets/e103b599-ff48-444b-b22c-0d11028709b3)

First line is the command that it receives, the rest is the error that is thrown.

**Comment by SuperBo** [comment]
@damian-elenbaas, happy that you are now able to use new features 👯
