### ISSUE TITLE
feature: reset a file/discard changes

### ISSUE THREAD

**Issue by ceuk** [SuperBo/fugit2.nvim#11]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

In other git TUI clients (e.g. lazygit) it's possible to press `d` on a file and have the option to "discard" staged/unstaged/all changes. This is a really useful feature. You can also do it per-line in a file in lazygit which is also handy. 

### Describe the solution you'd like

The ability to reset file changes or perform a checkout on a file

### Describe alternatives you've considered

I don't think there are any

**Comment by SuperBo** [comment]
Because "d" is dedicated for "Diff" menu. I think I will need to bind this behaviour to "D" or "x" key.

**Comment by SuperBo** [comment]
Whole file discard is implemented via https://github.com/SuperBo/fugit2.nvim/pull/23.
Now I need to implement per hunk discard.

**Comment by jdrupal-dev** [comment]
@SuperBo Cool, however this does not remove untracked (added) files.
What about using https://libgit2.org/libgit2/#HEAD/group/reset/git_reset with reset_type = HARD?

**Comment by SuperBo** [comment]
Hi @jdrupal-dev, untracked files are files which is not managed by git. There are two cases here

- Untracked file is not in staged: nothing is recorded by git, you are free to discard by deleting it, edit it. Fugit2 won't delete it because we don't want to accidentally delete user code.
- Untracked file is in staged: now the file is partially record by git in index. Discarding will remove any changes that is different than staged file.

So I think current behavior is safe and usable.

**Comment by SuperBo** [comment]
Hi, hunk/lines discard in unstaged patch view is enable via this patch

https://github.com/SuperBo/fugit2.nvim/pull/24.

@ceuk, @jdrupal-dev , please help me confirm if it works for you.

**Comment by ceuk** [comment]
Seems to work great - the only thing I noticed is the selecting the no option looks a bit off

This is yes:

![image](https://github.com/SuperBo/fugit2.nvim/assets/1681236/9cb55b99-6cd4-4af1-a058-43b6b25ecbef)

This is no:

![image](https://github.com/SuperBo/fugit2.nvim/assets/1681236/a8bad5b6-875e-4295-b107-6b9eb537aa46)

**Comment by SuperBo** [comment]
@ceuk, another bug with UI :)). For now, you can press "Y" to accept, "N" for no :D.

**Comment by SuperBo** [comment]
Fixed UI big https://github.com/SuperBo/fugit2.nvim/commit/3b9a7799c6bee88d4436e1f5155635e1c6e0bfab.

Close this issue. Feel free to reopen if you find any other error @ceuk, @jdrupal-dev.
