### ISSUE TITLE
feature: Diff split like fugitive

### ISSUE THREAD

**Issue by jcorbin** [SuperBo/fugit2.nvim#13]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

The one thing keeping me stuck on fugitive is its :GSplit feature, which allows me to never need to run git-add-p in practice.

### Describe the solution you'd like

A simple diff split mode:
- the key feature that a plugin needs to provide, is the ability to directly edit a git stage blob
- from there it’s mostly a matter of regular vimdiff features and editing

### Describe alternatives you've considered

Was hoping that diffview.nvim would work, allowing me to switch off fugitive to it plus a lua native porcelain like neogit (or fugit2…). But their focus on multi vcs abstraction, and fancy tree spanning changeset orientation doesn’t work well for me: https://github.com/sindrets/diffview.nvim/issues/471

**Comment by SuperBo** [comment]
Hello @jcorbin, for now, please install diffview.nvim as dependency. Then when you press "d d", you will be navigate to diffview.nvim tab.

I also included a patch view. Press "=" to toggle it.

<img width="1516" alt="Screenshot 2024-03-21 at 00 03 08" src="https://github.com/SuperBo/fugit2.nvim/assets/2666479/6db6272f-06c4-4293-86f7-e78627ca929d">


Will include a full diff view later.

**Comment by SuperBo** [comment]
hi @jcorbin, I implemented diffview, you can now trigger it by pressing `dd` or call command `Fugit2Diff`

**Comment by SuperBo** [comment]
Will close for now
