### ISSUE TITLE
feature: package for luarocks 

### ISSUE THREAD

**Issue by mrcjkb** [SuperBo/fugit2.nvim#14]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

This looks like a great candidate to package for luarocks, so with [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim), the installation could be simplified to `:Rocks install fugit2`.

### Describe the solution you'd like

It'd be more than happy to open a PR if you're open to it.

### Describe alternatives you've considered

N/A

### Additional context

It might be possible to package libgit2 for luarocks, and link to it.
I've successfully done so for most of the tree-sitter parsers.

**Comment by SuperBo** [comment]
Hi @mrcjkb , I am very happy to push this one to luarocks.

You can guide me how to do it. Any pull requests are also welcome. Will take a look at rocks.nvim after I fixed other bugs. 

Thank you!

**Comment by mrcjkb** [comment]
Awesome 🚀 

We have [a tutorial](https://github.com/nvim-neorocks/sample-luarocks-plugin) with a recommended approach that automates everything with conventional commits.
But if your plugin is still unstable, you might want to use 0-ver.

While it is also possible to not use tags and push `scm` rockspecs, I wouldn't recommend it, because it makes it difficult for users to roll back in case something breaks between updates.

Because of the libgit2 dependency, this repo might need a custom rockspec template that searches for the relevant libraries or headers - which I'd be happy to implement.
Or, if it makes sense, I could try to package libgit2 as a lua rock (maybe including lua bindings?), so that users wouldn't have to install it manually.

**Comment by SuperBo** [comment]
@mrcjkb , libgit2 lua binding is implemented by me via luajit ffi. I don't use https://github.com/libgit2/luagit2 because it is so outdated.

Do we need to make the lua binding codes a separate repo?

**Comment by mrcjkb** [comment]
Awesome! Thanks for supporting this :smile:
