### ISSUE TITLE
bug: Readme lazy.nvim install snippet is missing comma

### ISSUE THREAD

**Issue by TomRomeo** [SuperBo/fugit2.nvim#15]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.4

### Describe the bug

Hey thank you for this awesome plugin, it looks really nice!
In the installation snippet for lazy.nvim, there is a comma that is missing after the repository name. After adding it, lazy.nvim can successfully install Fugit2!
If it is okay, I can open a PR with the fix but you can also do it yourself :)

### Steps To Reproduce

1. Look at the readme Lazy.nvim installation instructions

### Expected Behavior

With a comma after the repository name, the plugin should be installable

**Comment by scottmckendry** [comment]
I've fixed this in PR #16 ;)

**Comment by SuperBo** [comment]
Thank @TomRomeo , I merged https://github.com/SuperBo/fugit2.nvim/pull/16. It is fixed now.
