### ISSUE TITLE
bug: when accidentally switching out of fugit2Graph you cannot get back

### ISSUE THREAD

**Issue by sboesebeck** [SuperBo/fugit2.nvim#18]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

MacOS14.3.1

### Describe the bug

when a Fugit2 dialog is open and you switch to another window or open neotree for example, you cannot get back to the neogit2 dialog. If you type in `<CMD>Fugit2Graph`  for example again, you'd get a second dialog, you can use on top of the existing one (instead of reusing the already opened one). If you close that, the dialog stays open

### Steps To Reproduce

1. open a file in a git repository
2. open fugit2Graph dialog, e.g. `<CMD>Fugit2Graph`
3. open neotree or go to "next window"
4. try to close the dialog

### Expected Behavior

there might be two "solutions" to this:

- close the dialog as soon as the focus is lost. Might be annoying to accidenially close this all the time though
- reuse the dialog. So when opening it a 2nd time, I can close it.

Update: It only happens with `Fugit2Graph` and the `CTRL-W CTRL-W` gets the focus back...

**Comment by SuperBo** [comment]
Hi @sboesebeck, can you help me confirm the same issue happens with "Fugit2" main diaglog or just with "Fugit2Graph". I remembered implemented a dedup mechanism for main Fugit2 dialog, but not for Fugit2Graph.

Tips: you can use keys "Ctrl-W Ctrl-W" to go back to top popup without trigger the command again.

**Comment by sboesebeck** [comment]
I just tried it - you're right, it does not happen with "Fugit2" itself. And the `Ctrl-W Ctrl-W` - keybinding works. Thanks.

**Comment by SuperBo** [comment]
@sboesebeck, please check again :D, I fixed it
