### ISSUE TITLE
feature: integration with diffview

### ISSUE THREAD

**Issue by Feel-ix-343** [SuperBo/fugit2.nvim#19]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Diff

### Describe the solution you'd like

Diffview

### Describe alternatives you've considered

Na

### Additional context

Just diffview

Like neogit

**Comment by Feel-ix-343** [comment]
Oops

**Comment by Feel-ix-343** [comment]
This should be mentioned in the features, imo

**Comment by SuperBo** [comment]
@Feel-ix-343, I've just updated the README. I also planning to add my own diffview implementation to support in-memory index while rebasing.

For now, use diffview.nvim as a fallback support.
