### ISSUE TITLE
feature: Use the git repository of the current buffer instead of the cwd.

### ISSUE THREAD

**Issue by Kraust** [SuperBo/fugit2.nvim#26]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

I open up many git repositories in my instance of vim, to the point where using `cd` and `lcd` is not a viable solution (but can be used if absolutely necessary). Other git plugins derive the git repo from the open buffer's path and this is a workflow that works better for me.

### Describe the solution you'd like

I assume it has something to do with swapping out `cwd` here: https://github.com/SuperBo/fugit2.nvim/blob/55f3a90521f1f40c88afb2af2173567dc01d294b/lua/fugit2/init.lua#L39.

### Describe alternatives you've considered

Just using `cd` and `lcd` can solve the problem.

**Comment by SuperBo** [comment]
Hi @Kraust, this should be fixed in https://github.com/SuperBo/fugit2.nvim/pull/27.
Please let me know if this fix your problem.

**Comment by Kraust** [comment]
@SuperBo quick check and it looks like it works.

Thank you for the fast reply.
