### ISSUE TITLE
feature: Mark all changes in a directory for a commit

### ISSUE THREAD

**Issue by sboesebeck** [SuperBo/fugit2.nvim#28]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

When opening Fugit2 and you have a lot of changes it would be great, if hitting space on a directory would add all changes in that directory to the commit (similar as lazygit does it)

### Describe the solution you'd like

see above

### Describe alternatives you've considered

not sure about alternatives though. Maybe another keybinding.

**Comment by SuperBo** [comment]
Agree, this can easily be done. Can reuse the same code for visual mode staging.

Tips: you can toggle visual mode, select all file under one directory, then press "-", "space" or "s" for staging.

**Comment by sboesebeck** [comment]
Ah. yes, this is cool But not really what I meant: In your video, it would be a lot easier to just hit space `fugit2` and all changes in that directory would be added. But visual mode is of course also helpful, as vimmotions work.

**Comment by SuperBo** [comment]
@sboesebeck, I got your point, I think I can reuse the same visual staging code for this feature, please wait for my update

**Comment by SuperBo** [comment]
@sboesebeck, implemented this feature on latest changes. Please test :D.
