### ISSUE TITLE
feature: Copy highlighted SHA from Graph view

### ISSUE THREAD

**Issue by AquilesGomez** [SuperBo/fugit2.nvim#32]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

I like the graph view, but I'm a bit frustrated that I can't directly copy the selected commit from there.

### Describe the solution you'd like

A shortcut to copy the currently selected commit SHA would be immensely helpful

### Describe alternatives you've considered

The easiest alternative is to use `git rev-parse HEAD~n`.

**Comment by SuperBo** [comment]
Hi @AquilesGomez, here you are https://github.com/SuperBo/fugit2.nvim/pull/33

- Press "**yy**" to yank the SHA id.
- Press "**yc**" to yank SHA id to the clipboard.

**Comment by AquilesGomez** [comment]
Amazing thank you!
