### ISSUE TITLE
feature: Support fzf-lua

### ISSUE THREAD

**Issue by ryancobb** [SuperBo/fugit2.nvim#38]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Viewing branches requires the telescope plugin. I use fzf-lua as an alternative and receive the error `Command not found: Telescope` when trying to view branches.

### Describe the solution you'd like

Support fzf-lua when selecting branches and any other future interaction where telescope might be used

A quick fix could be to change[ this section](https://github.com/SuperBo/fugit2.nvim/blob/046ee5ba791bd198b0a6fbf3b738ffb0db29fe1c/lua/fugit2/view/git_status.lua#L1687-L1692) to:

```lua
      if vim.fn.exists ":Telescope" > 0 then
        self:unmount()
        vim.cmd { cmd = "Telescope", args = { "git_branches" } }
      elseif vim.fn.exists ":FzfLua" > 0 then
        self:unmount()
        vim.cmd { cmd = "FzfLua", args = { "git_branches" } }
      else
        vim.notify "[Fugit2] No telescope or fzf-lua"
      end
```

### Describe alternatives you've considered

I considered switching to telescope, but I prefer fzf-lua.

**Comment by SuperBo** [comment]
@ryancobb , Thank you 🙏 for your idea. You don't need to switch to Telescope anymore.

https://github.com/SuperBo/fugit2.nvim/pull/39

This feature should be implemented natively. Use Telescope or FzfLua is just temporary.

**Comment by SuperBo** [comment]
Hi @ryancobb , you are right, my mistake with code. New fix is up, https://github.com/SuperBo/fugit2.nvim/pull/40.

Can you test it?

**Comment by ryancobb** [comment]
Works great! Thanks @SuperBo - big fan of the plugin.

**Comment by SuperBo** [comment]
Thank you @ryancobb, just report and bug you found or raise any idea, I will try to implement small features and bug fixes asap.
