### ISSUE TITLE
bug: Push/Pull actions use working directory instead of currently open buffer's git path.

### ISSUE THREAD

**Issue by Kraust** [SuperBo/fugit2.nvim#53]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

NixOS Unstable

### Describe the bug

When doing either a pull or push (and maybe other operations too), It looks like fugit2 uses my buffer's working directory `cd` to derive the git root instead of the file name.

### Steps To Reproduce

1. Open up a file under source control in the working directory of your git project.
2. `:cd ~/`
3. `:Fugit2`
4. either do P or p.
5. In Pull's case you will get something like this:
```
❯ git pull origin
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
FAILED 128
```

### Expected Behavior

I expect my open buffer to take priority in finding the git root than my wd as I am rarely in the same wd as my open buffer.

**Comment by SuperBo** [comment]
Acknowledged, fix will come soon 👍

**Comment by SuperBo** [comment]
hi @Kraust, fixed in PR https://github.com/SuperBo/fugit2.nvim/pull/55. Can you confirm that it works?

**Comment by Kraust** [comment]
After another quick look the branch command is also affected by this bug.

Otherwise push and pull looked like they worked for me.

**Comment by SuperBo** [comment]
Are you using FzfLua or Telescope?

**Comment by Kraust** [comment]
The error is referencing telescope:

```
E5108: Error executing lua: ...are/nvim/lazy/fugit2.nvim/lua/fugit2/view/git_status.lua:1677: Vim:Error executing Lua callback: ...nvim/lazy/telescope.nvim/lua/telescope/builtin/__git.lua:448: /home/rdupuis is not a git directory
stack traceback:
	[C]: in function 'error'
	...nvim/lazy/telescope.nvim/lua/telescope/builtin/__git.lua:448: in function 'try_worktrees'
	...nvim/lazy/telescope.nvim/lua/telescope/builtin/__git.lua:481: in function 'set_opts_cwd'
	...nvim/lazy/telescope.nvim/lua/telescope/builtin/__git.lua:497: in function 'v'
	.../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:580: in function <.../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:539>
	...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:188: in function 'run_command'
	...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:259: in function 'load_command'
	...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:108: in function <...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:107>
	[C]: in function 'cmd'
	...are/nvim/lazy/fugit2.nvim/lua/fugit2/view/git_status.lua:1677: in function '_submit_fn'
	...im/lazy/fugit2.nvim/lua/fugit2/view/components/menus.lua:322: in function <...im/lazy/fugit2.nvim/lua/fugit2/view/components/menus.lua:318>
stack traceback:
	[C]: in function 'cmd'
	...are/nvim/lazy/fugit2.nvim/lua/fugit2/view/git_status.lua:1677: in function '_submit_fn'
	...im/lazy/fugit2.nvim/lua/fugit2/view/components/menus.lua:322: in function <...im/lazy/fugit2.nvim/lua/fugit2/view/components/menus.lua:318>
```

I have no issues switching to something else or configuring fugit2 differently.

**Comment by SuperBo** [comment]
@Kraust, please pull latest commit. It should fix git branch problem

**Comment by Kraust** [comment]
Looking good. Closing.
