### ISSUE TITLE
bug: popup win height becomes negative when terminal zoomed in too much

### ISSUE THREAD

**Issue by konosubakonoakua** [SuperBo/fugit2.nvim#63]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

ubuntu 22

### Describe the bug

popup win height becomes negative when terminal zoomed in too much using `<C-+>`

```
Error executing Lua callback: ...a/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:168: 'height' key must be a positive Integer
stack traceback:
	[C]: in function 'nvim_open_win'
	...a/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:168: in function '_open_window'
	...a/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:251: in function 'mount'
	....local/share/nvim/lazy/nui.nvim/lua/nui/layout/float.lua:143: in function 'mount_box'
	.../.local/share/nvim/lazy/nui.nvim/lua/nui/layout/init.lua:309: in function 'mount'
	...are/nvim/lazy/fugit2.nvim/lua/fugit2/view/git_status.lua:1076: in function 'mount'
	...a/.local/share/nvim/lazy/fugit2.nvim/lua/fugit2/init.lua:90: in function <...a/.local/share/nvim/lazy/fugit2.nvim/lua/fugit2/init.lua:86>

```

### Steps To Reproduce

zoom terminal in, execute `:Fugit2`

### Expected Behavior

open popup normally

**Comment by SuperBo** [comment]
Hi @konosubakonoakua, this bug maybe related to [nui.nvim](MunifTanjim/nui.nvim). Let me file  issue in upstream nui repo.

**Comment by SuperBo** [comment]
Dear @konosubakonoakua, I raised a bug here https://github.com/MunifTanjim/nui.nvim/issues/371.

While waiting for the bug to be fixed upstream. You can fix this bug by setting `height = '80%'` or some absolute number to fix this.

**Comment by SuperBo** [comment]
@konosubakonoakua, I think upstream `nui.nvim` is already updated https://github.com/MunifTanjim/nui.nvim/issues/371. You can check it out.
