### ISSUE TITLE
[Question?] In the graph view, the number of commits are limited (say only 20)

### ISSUE THREAD

**Issue by bowentan** [SuperBo/fugit2.nvim#66]
The number of commits displayed in the graph view is limited and I can't scroll more to see additional commits. Is it a setting missing? Also, the commit does not show the date of commit, is it also a setup mistake?

**Comment by SuperBo** [comment]
@bowentan, sorry, that's the initial implementation of lazy loading, I forgot to implement real lazy load >.<.
` Also, the commit does not show the date of commit` -> I forgot to render it in second lines.

TODO List:

- Implement lazy loading .
- Render commit date in graph.

**Comment by SuperBo** [comment]
Hi @bowentan, I fixed these issue in https://github.com/SuperBo/fugit2.nvim/pull/76. Can you help verify it works on your end?
