### ISSUE TITLE
feature: provide path for libgpgme

### ISSUE THREAD

**Issue by sagarc03** [SuperBo/fugit2.nvim#67]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

https://github.com/SuperBo/fugit2.nvim/blob/97ac2c91c11a44fa84b0644c1ec02ade0bb6ce0d/lua/fugit2/gpgme.lua#L242-L244

I am installing gpgme using brew and it's not available at the path which `ffi` expects. When i change the value at line `243` to hard path to everything works fine.

### Describe the solution you'd like

Provide path via set up config.

### Describe alternatives you've considered

I am tried changing path but it has potential of breaking other builds.

### Additional context

NA

**Comment by SuperBo** [comment]
@sagarc03 , hello, will fix this bug tomorrow :D.
Thank for using my plugin

**Comment by sagarc03** [comment]
Oh man thank you for making this awesome plugin. This feels like a much more natural git integration with Neovim. I not familar with lua to make a direct contribution but I would love to help in anyway.

Also `feature` not a `bug`

**Comment by SuperBo** [comment]
@sagarc03, implemented in this https://github.com/SuperBo/fugit2.nvim/pull/69. Can you help me verify it works?

**Comment by sagarc03** [comment]
@SuperBo seems to be working as expected
