### ISSUE TITLE
bug: hunk granularity

### ISSUE THREAD

**Issue by ceuk** [SuperBo/fugit2.nvim#7]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Arch Linux

### Describe the bug

I think this might be more of an issue with the upstream libgit2 library maybe but hunk staging doesn't work as I'd expect. e.g. in Lazygit I'm able to stage and unstage individual lines even. Perhaps this isn't representative of a canonical "hunk" in a git sense, but it's a bit restrictive e.g. if I have some staged changes and make some other changes elsewhere in the file, then stage said changes, they become part of the same hunk when it's not clear why

## (un)staging granularity 

1. Create a file with 10 lines of text and commit it
2. Change 3-4 unrelated lines and attempt to stage one of them
3. All changes are staged

## Hunks unexpectedly merged
1. Create a file with 10 lines of text and commit it
2. Change the first line and save the file
4. Stage the change
5. Change the last line and save the file
6. Stage the change
7. Hunks are merged

### Expected Behavior

See above

**Comment by SuperBo** [comment]
Will take a look, stage and unstage logic is implemented by me because libgit2 doesn't support apply a hunk yet. Literally, this is my bug :D

**Comment by SuperBo** [comment]
@ceuk, Please enter visual mode (Pressing v) for lines stage/unstage.

**Comment by ceuk** [comment]
@SuperBo that is so cool. What a great idea! Works a treat

**Comment by SuperBo** [comment]
@ceuk, I work my ass off for this line stage/unstage feature because Libgit2 doesn't support it natively :)).
