### ISSUE TITLE
bug: signed init commit aka first commit fails 

### ISSUE THREAD

**Issue by sagarc03** [SuperBo/fugit2.nvim#73]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Operating system/version

macOs Sonoma 14.5

### Describe the bug

Initial commit failed with following error "[Fugit2] Failed to get git head. Error code -9" when using signed commit.

### Steps To Reproduce

1. Create a new git repo
2. Create a README.md add random text
3. Open Neovim and try to init signed commit via Fugit

### Expected Behavior

Create a signed commit

**Comment by SuperBo** [comment]
Hi @sagarc03, https://github.com/SuperBo/fugit2.nvim/pull/75 should fix this bug. Can you verify it works?

**Comment by sagarc03** [comment]
seems to be working perfect

**Comment by SuperBo** [comment]
Thank @sagarc03 for your report. I seems to overlook this.
