### ISSUE TITLE
bug: Failed to run `config` for fugit2.nvim ... color.lua:47: attempt to compare nil with number

### ISSUE THREAD

**Issue by idanarye** [SuperBo/fugit2.nvim#74]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Operating system/version

Arch Linux 6.9.3-arch1-1

### Describe the bug

When Fugit2's `setup` is called I get the following error:

```
Failed to run `config` for fugit2.nvim
...ocal/share/nvim/lazy/fugit2.nvim/lua/fugit2/hl/color.lua:47: attempt to compare nil with number
# stacktrace:
  - /fugit2.nvim/lua/fugit2/hl/color.lua:47 _in_ **rgba_from_hex**
  - /fugit2.nvim/lua/fugit2/hl/color.lua:182 _in_ **generate_palette**
  - /fugit2.nvim/lua/fugit2/view/colors.lua:119 _in_ **set_hl**
  - /fugit2.nvim/lua/fugit2/init.lua:26 _in_ **setup**
```

I think it is related to the fact I don't pass a `colorscheme`, but according to the documentation overriding the colorscheme should be optional.

From a quick bisection, it looks like the bug was introduced in this commit: c1350b926d29ea1bb8a64dc60c75fc3734f62181.

### Steps To Reproduce

1. Create a file named `test-init.lua` with the following content:
    ```lua
    -- This part is copied from Lazy.nvim's README:
    local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
    if not (vim.uv or vim.loop).fs_stat(lazypath) then
      vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
      })
    end
    vim.opt.rtp:prepend(lazypath)

    -- This part is copied from Fugit2's README:
    require"lazy".setup {
        {
            'SuperBo/fugit2.nvim',
            opts = {
                width = 70,
            },
            dependencies = {
                'MunifTanjim/nui.nvim',
                'nvim-tree/nvim-web-devicons',
                'nvim-lua/plenary.nvim',
                {
                    'chrisgrieser/nvim-tinygit', -- optional: for Github PR view
                    dependencies = { 'stevearc/dressing.nvim' }
                },
            },
            cmd = { 'Fugit2', 'Fugit2Diff', 'Fugit2Graph' },
            keys = {
                { '<leader>F', mode = 'n', '<cmd>Fugit2<cr>' }
            }
        },
    }
    ```
2. Run `nvim -u test-init-lua`
3. Inside Neovim, run `:Fugit2<Cr>` (it's the `setup` that causes it, but with that default configuration you need to run a command in order to trigger the setup)

### Expected Behavior

I would expect it to work without triggering an error.

**Comment by Twotyth** [comment]
+1, reproduces the same ; os=win11

**Comment by SuperBo** [comment]
Hi @Twotyth, @idanarye , this should be fix by this commit https://github.com/SuperBo/fugit2.nvim/commit/f7b4153bb084b1eb81cbd0ea77f2281a896b0766.

This error happen because I setup BlameColor based on TODO color and I assuming that TODO highlight group will have some background like in Catppuccin or Duskfox theme.

Could you guys share with me your current color scheme?

**Comment by idanarye** [comment]
I'm using [Carbonfox](https://github.com/EdenEast/nightfox.nvim/?tab=readme-ov-file#carbonfox) (one of the nightfox.nvim variants)

And it works now. Thanks!
