### ISSUE TITLE
Installation experience / doc improvement suggestions

### ISSUE THREAD

**Issue by Anrock** [SuperBo/fugit2.nvim#77]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

I'm using neovim 0.11.0 and Rocks.
 
I've checked [installation section](https://github.com/SuperBo/fugit2.nvim#-installation) in README and made sure I have libgit2 installed via my package manager.

I've checked corresponding [Rocks](https://github.com/SuperBo/fugit2.nvim?tab=readme-ov-file#rocksnvim) section which told me I don't need anything else except just installing the plugin.

I've executed `:Rocks install fugit2.nvim` and plugin was succesfully installed

I've restarted my neovim and executed `:Fugit2` (I was already in git repo), got an error:
```
Error executing Lua callback: ...in/.local/share/nvim/rocks/rocks_rtp/lua/fugit2/git2.lua:1972: attempt to index field 'C' (a nil value)
stack traceback:
        ...in/.local/share/nvim/rocks/rocks_rtp/lua/fugit2/git2.lua:1972: in function 'open'
        ...in/.local/share/nvim/rocks/rocks_rtp/lua/fugit2/init.lua:68: in function 'open_repository'
        ...in/.local/share/nvim/rocks/rocks_rtp/lua/fugit2/init.lua:87: in function <...in/.local/share/nvim/rocks/rocks_rtp/lua/fugit2/init.lua:86>
```

I've rechecked the README file and found there is separate [installation guide](https://github.com/SuperBo/fugit2.nvim/wiki/%F0%9F%93%A6-Installation). First part was copypasted from README for some reason but there was a section about libgit2.

Apparently I have to set libgit2 path in plugin config. All examples for setting libgit2 are given using some specific package manager I don't use.

I've checked plugin source code to see how it's configured. The usual `require(...).setup({...})` it seems. I've added setup call to my config, restarted neovim and tried executing `:Fugit2` and now I got:
```
Error executing Lua callback: .../rocks_rtp/lua/fugit2/view/components/file_tree_view.lua:9: module 'nvim-web-devicons' not found:Failed loading module nvim-web-devicons in LuaRocks rock nvim
-web-devicons 0.99-1
        no field package.preload['nvim-web-devicons']
        no file './nvim-web-devicons.lua'
        no file '/usr/share/luajit-2.1/nvim-web-devicons.lua'
        no file '/usr/local/share/lua/5.1/nvim-web-devicons.lua'
        no file '/usr/local/share/lua/5.1/nvim-web-devicons/init.lua'
        no file '/usr/share/lua/5.1/nvim-web-devicons.lua'
        no file '/usr/share/lua/5.1/nvim-web-devicons/init.lua'
        no file '/home/shtepin/.local/share/nvim/rocks/share/lua/5.1/nvim-web-devicons.lua'
        no file '/home/shtepin/.local/share/nvim/rocks/share/lua/5.1/nvim-web-devicons/init.lua'
        no file '/usr/share/lua/5.1/init.lua'
        no file './nvim-web-devicons.so'
        no file '/usr/local/lib/lua/5.1/nvim-web-devicons.so'
        no file '/usr/lib64/lua/5.1/nvim-web-devicons.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/shtepin/.local/share/nvim/rocks/lib/lua/5.1/nvim-web-devicons.so'
        no file '/home/shtepin/.local/share/nvim/rocks/lib64/lua/5.1/nvim-web-devicons.so'
stack traceback:
        [C]: in function 'require'
        .../rocks_rtp/lua/fugit2/view/components/file_tree_view.lua:9: in main chunk
        [C]: in function 'require'
        ...hare/nvim/rocks/rocks_rtp/lua/fugit2/view/git_status.lua:16: in main chunk
        [C]: in function 'require'
        ....local/share/nvim/rocks/share/lua/5.1/fugit2/view/ui.lua:19: in function 'new_fugit2_status_window'
        ...in/.local/share/nvim/rocks/share/lua/5.1/fugit2/init.lua:89: in function <...in/.local/share/nvim/rocks/share/lua/5.1/fugit2/init.lua:86>
```

Weird. Neither README, nor Installation Guide mentioned that I need nvim-web-devicons. I also expected `Rocks` to bring any dependencies that plugin has - after all it's the main selling point of using luarocks for plugins. I've also looked at other wiki pages and searched the issues but I've no mention of that dependency (even optional) and also haven't found an option to turn it off.

### Describe the solution you'd like

Mention that you need to configure libgit2 path explicitly in the readme.

Make plugin log more user-frienly error in case libgit2 path isn't configured or something else is wrong with libgit2

Mention that nvim-web-dev-icons is required dependency or fix plugin crashing if it can't find it.

Installation guide could be more convenient if it was restructed into sections that go in order like libgit2 installation, plugin installation, plugin configuration where each section describes different ways/OS-specifics to achieve section goal instead of current inside-out approach where different ways/OSes are separate sections which we'll have to repeat same snippets for each OS.

### Describe alternatives you've considered

Keep debugging this plugin until it finally works on my machine. Abandon this and try using another plugin. Keep using tig for git things.

**Comment by SuperBo** [comment]
Hi @Anrock, I'm very sorry to hear about your experience. As you can see in luarock package https://luarocks.org/modules/superbo/fugit2.nvim, [nvim-web-devicons](https://luarocks.org/modules/nvim-tree/nvim-web-devicons) is already listed as dependencies, I don't know why it is not installed when you use with `Rocks install`. Can you share with me your config file so I can replicate this on my local machine.

About this suggestion `Installation guide could be more convenient if it was restructed into sections that go in order like libgit2 installation, plugin installation, plugin configuration where each section describes different ways/OS-specifics to achieve section goal instead of current inside-out approach where different ways/OSes are separate sections which we'll have to repeat same snippets for each OS.` I will restructure wiki following your suggestion. Thank you for this idea.

**Comment by Anrock** [comment]
@SuperBo don't be sorry and please excuse me if it sounded like some kind of personal attack.

Anyway, here's my config
<details><summary>Details</summary>

```

-- Rocks
local rocks_config = {
    rocks_path = vim.fn.stdpath("data") .. "/rocks",
    luarocks_binary = "luarocks",
}

vim.g.rocks_nvim = rocks_config

local luarocks_path = {
    vim.fs.joinpath(rocks_config.rocks_path, "share", "lua", "5.1", "?.lua"),
    vim.fs.joinpath(rocks_config.rocks_path, "share", "lua", "5.1", "?", "init.lua"),
}
package.path = package.path .. ";" .. table.concat(luarocks_path, ";")

local luarocks_cpath = {
    vim.fs.joinpath(rocks_config.rocks_path, "lib", "lua", "5.1", "?.so"),
    vim.fs.joinpath(rocks_config.rocks_path, "lib64", "lua", "5.1", "?.so"),
}
package.cpath = package.cpath .. ";" .. table.concat(luarocks_cpath, ";")

vim.opt.runtimepath:append(vim.fs.joinpath(rocks_config.rocks_path, "lib", "luarocks", "rocks-5.1", "rocks.nvim", "*"))

--
vim.g.mapleader = " "

-- require "paq" {
--   'hrsh7th/cmp-calc';
--   'hrsh7th/cmp-nvim-lua';
--   'rasulomaroff/cmp-bufname';
--   'hrsh7th/cmp-nvim-lsp-signature-help';
-- 
--   -- Other
--   'kana/vim-textobj-user';
-- }

require('neorg').setup({
  load = {
    ["core.defaults"] = {},
    ["core.dirman"] = {
      config = {
        workspaces = {
          main = "~/Norg",
        },
        default_workspace = "main",
      },
    },
    ["core.qol.toc"] = {},
    ["core.summary"] = {},
    ["core.completion"] = {
      config = {
        engine = "nvim-cmp",
      },
    },
    ["core.concealer"] = {
      config = {
        icons = {
          todo = {
            done = { icon = "✓" },
            pending = { icon = "▶" },
            uncertain = { icon = "⁇" },
            on_hold = { icon = "⏸" },
            cancelled = { icon = "⏏" },
            undone = { icon = " " },
          },
        },
      },
    },
  }
})

require('fugit2').setup({
  opts = {
    libgit2_path = '/usr/lib64/libgit2.so'
  }
})

--require('gitsigns').setup()

vim.filetype.add({
  extension = {
    cf = "ebnf", -- For BNFC .cf files
    ltx = "ini", -- Stalker ini files
    script = "lua", -- Stalker lua scripts
  },
})

-- Diagram drawing
vim.api.nvim_set_keymap('v', '<leader>v', ':VBox<CR>', {silent = true, noremap = true})

-- Theme / statusline
vim.opt.termguicolors = true
vim.opt.background = 'dark'
vim.cmd.colorscheme('gruvbox')
require('feline').setup()

-- LSP
require('lsp')

-- Completion
vim.opt.completeopt = {'menuone', 'noinsert', 'noselect'}
local cmp = require('cmp')
cmp.setup({
  snippet = {
    expand = function(args)
      -- Native neovim snippet support
      vim.snippet.expand(args.body)
    end
  },
  mapping = cmp.mapping.preset.insert({
    ['<C-b>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
  }),
  sources = cmp.config.sources(
    { { name = 'nvim_lsp' }, },
    { { name = 'buffer' }, },
    { { name = 'bufname' }, },
    { { name = 'calc' }, },
    { { name = 'nvim_lsp_signature_help' } },
    { { name = 'path', option = { trailing_slash = true } } },
    { { name = 'nvim_lua' } }
  ),
})

-- Set configuration for specific filetype.
cmp.setup.filetype('gitcommit', {
  sources = cmp.config.sources({
    { name = 'git' }, -- You can specify the `git` source if [you were installed it](https://github.com/petertriho/cmp-git).
  }, {
    { name = 'buffer' },
  })
})

-- Use buffer source for `/` and `?` (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline({ '/', '?' }, {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    { name = 'buffer' }
  }
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(':', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = cmp.config.sources({
    { name = 'path', option = { trailing_slash = true } }
  }, {
    { name = 'cmdline' }
  })
})

vim.api.nvim_set_keymap('n', '<leader>ff', '<Cmd>Telescope find_files<CR>', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fg', '<Cmd>Telescope live_grep<CR>', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fr', '<Cmd>Telescope lsp_references<CR>', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fd', '<Cmd>Telescope diagnostics bufnr=0<CR>', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fD', '<Cmd>Telescope diagnostics<CR>', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fs', '<Cmd>Telescope lsp_document_symbols<CR>', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fS', '<Cmd>Telescope lsp_dynamic_workspace_symbols<CR>', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fb', '<Cmd>Telescope buffers<CR>', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fi', '<Cmd>Telescope lsp_incoming_calls<CR>', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fo', '<Cmd>Telescope lsp_outgoing_calls<CR>', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>fR', '<Cmd>Telescope resume<CR>', {silent = true, noremap = true})

require('oil').setup()
vim.api.nvim_set_keymap('n', '<leader>o', '<Cmd>Oil --float<CR>', {silent = true, noremap = true})

require('neovide')

-- Indents
vim.opt.listchars = {
  tab = '│·',
  extends = '⟩',
  precedes = '⟨',
  trail = '·'
}
vim.opt.list = true
vim.opt.cursorline = true
vim.opt.cursorcolumn = true
vim.opt.colorcolumn = '80'
vim.opt.textwidth = 80
vim.opt.softtabstop = 2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2

-- Sign column
vim.opt.number = true

-- Search
vim.opt.inccommand = 'split'
vim.opt.showmatch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.shortmess = 'c'

-- Netrw
vim.g.netrw_liststyle = 3
vim.g.netrw_banner = 0
vim.g.netrw_preview = 1

-- Misc
vim.opt.showmode = false
vim.opt.mouse = 'a'
vim.opt.updatetime = 300
vim.opt.scrolloff = 3
vim.opt.langmap = 'ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯЖ;ABCDEFGHIJKLMNOPQRSTUVWXYZ:,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz'
vim.opt.belloff = vim.opt.belloff + 'ctrlg'
vim.opt.conceallevel = 2
```
</details> 

And rocks.toml file
<details><summary>Details</summary>

```
# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.31.3"
"fidget.nvim" = "1.4.1"
"gruvbox.nvim" = { version = "2.0.0", opt = true }
"oil.nvim" = "2.10.0"
"telescope.nvim" = "scm"
"venn.nvim" = "scm"
"which-key.nvim" = "2.1.0"
cmp-buffer = "scm"
cmp-cmdline = "scm"
cmp-nvim-lsp = "scm"
cmp-path = "scm"
neorg = { version = "8.7.1" }
nvim-lspconfig = "0.1.8"
"rocks-treesitter.nvim" = "scm"
tree-sitter-toml = "scm"
tree-sitter-lua = "scm"
tree-sitter-haskell = "scm"
tree-sitter-ebnf = "scm"
tree-sitter-markdown = "scm"
"feline.nvim" = "1.6.2"
tree-sitter-starlark = "scm"
tree-sitter-make = "scm"
tree-sitter-bash = "scm"
tree-sitter-c = "scm"
tree-sitter-cmake = "scm"
tree-sitter-kconfig = "scm"
tree-sitter-yaml = "scm"
"rocks-git.nvim" = "1.5.1"
tree-sitter-norg-meta = "0.1.0"
tree-sitter-python = "scm"
tree-sitter-vimdoc = "scm"
"fugit2.nvim" = "0.2.0"
nvim-cmp= "scm"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"
```
</details> 

One interesting thing I've noticed is that while devicons are indeed in dependency file - Rocks install it. But I do have other deps: nui and plenary (maybe from other plugins). Could be an issue with Rocks actually.

**Comment by SuperBo** [comment]
thank @Anrock, I need to create an isolated neovim config to test your config, so it may take a while. Do you manage to run Fugit2?

P/s: `nui` and `plenary` is also in dependencies list. You can see lazy.nvim config to see all dependencies :D

**Comment by Anrock** [comment]
Oops, I messed up my previous message. What I meant is that nui and plenary were installed by Rocks but nvim-web-devicons wasn't, for some reason. But I probably had nui and plenary because I have neorg installed. Could be something wrong with Rocks.

Anyway, I installed devicons manually via Rocks and Fugit2 starts without errors now.

**Comment by SuperBo** [comment]
@Anrock, I write a dedicated part for libgit2 installation. https://github.com/SuperBo/fugit2.nvim/wiki/Install-libgit2. Do you have anything to add?

**Comment by Anrock** [comment]
@SuperBo I guess no, except it seems it's just a copy of whatever was before in installation guide? With same config copypasted under each section for each OS over and over. I was thinking about remaking installation guide into something like:

# Install Fugit2
## Rocks
`:Rocks install fugit2.nvim`
## Lazy
whatever is needed for lazy
## Some other package manager
...

# Install libgit2
## Ubuntu
`sudo apt-get install libgit2`
## Arch Linux
`sudo pacman -S libgit2`
## some other OS
...

# Specify path to libgit2 in Fugit2 setup
how to get actual path to libgit2.so goes here
## Lazy
```
-- Fugit2 setup table
{
  libgit2_path = 'libgit2.so.1.7',
  ...
}
```
## Rocks
`require('fugit2.nvim').setup({ libgit2_path = ... })`
## some other package manager
...

**Comment by bitterjug** [comment]
Hi. I'm here with the same problem after searching for "attempt to index field 'C'"
Today I was excited to see fugit2 and wanted to try it. I installed an appimage of neovim 10 specially for the purpose. And installed Rocks because that's what the readme said. (My other config uses lazy). 

Then I did `Rocks install fugit2.nvim` because that's what the Readme said. (I was also curious to try out Rocks for first time) 
![image](https://github.com/SuperBo/fugit2.nvim/assets/495718/8c2a4deb-ae69-4a62-adff-099b1822875e)

Running `:Fugit2` now gives:
```
Error executing Lua callback: ...cal/share/nvim-rocks/rocks/rocks_rtp/lua/fugit2/git2.lua:1972: attempt to index field 'C' (a nil value)
stack traceback:
        ...cal/share/nvim-rocks/rocks/rocks_rtp/lua/fugit2/git2.lua:1972: in function 'open'
        ...cal/share/nvim-rocks/rocks/rocks_rtp/lua/fugit2/init.lua:68: in function 'open_repository'
        ...cal/share/nvim-rocks/rocks/rocks_rtp/lua/fugit2/init.lua:87: in function <...cal/share/nvim-rocks/rocks/rocks_rtp/lua/fugit2/init.lua:86>
```

nvim
```
:version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run ":verbose version" for more info
```

**Comment by SuperBo** [comment]
@bitterjug, sorry for your experience. I didn't test with rocks installation before :(. I will try to fix this asap T_T.

**Comment by SuperBo** [comment]
hi @bitterjug, @Anrock can you test new installation guide mentioned here.

- https://github.com/SuperBo/fugit2.nvim/wiki/%F0%9F%93%A6-Installation
- https://github.com/SuperBo/fugit2.nvim/wiki/Install-libgit2

**Comment by Anrock** [comment]
@SuperBo looks great. Small nitpicks/suggestions:
- In Installation guide, Rocks section the wording makes it look like you absolutely have to use rocks-config.nvim installed. It's a nice utility/convenience plugin but it's not strictly required. My setup uses plain old `require('fugit2.nvim').setup(...)` and it works.
- Same place, there is a snippet for rocks.toml. I think it isn't needed, especially not as a separate entry in rocks.toml. Just executing `:Rocks install fugit2.nvim 2.0` should automatically add fugit2.nvim to plugin list (and potentially do other things automagically in future versions of rocks). 
- It may be a bad idea to mention specific version of fugit2 in the guide. Clueless user will execute command/insert snippet verbatim, locking himself to 2.0 while it may happen that 4.5 is already available. You'll have to update the guide with each new version released to avoid that. I think better way would be to just tell user to `:Rocks install fugit2.nvim` which should automatically pick up latest non-dev version, add it to rocks.toml thus potentially saving you and that user some headache.
- It shows setting `libgit2_path = "libgit2"` and that actually works (TIL). But in libgit2 installation guide (which user is supposed to read) it tells user to use other value for that option. This inconsistency between two guides which user is supposed to read one after the other may raise some WTFs. I suggest to leave `libgit2_path = "libgit2"` as default (and actually make it default value in options table?) since that will probably work for 80% of widespread OSes and only provide snippets with overriding for specific systems like MacOS, NixOS and so on. That way 80% of users who use mainstream OS like ubuntu will check the guide, see that for their mainstream OS the only thing needed is generic `sudo apt-get install libgit2` and the rest will work automagically using default values.

**Comment by SuperBo** [comment]
hi @Anrock, actually `libgit2_path = "libgit2"` is already the default value. However the problem with my plugin is that the `setup` function must be called once to set it up. So, the actual usage of section `[plugins."fugit2.nvim".config]` is just triggering setup function call.

For `require('fugit2.nvim').setup(...)`, where do you put it? In `init.lua` (after Rocks.nvim setup) or in a separate file?

Do you think it will be better if I separate `Rocks` installation guide from `lazy.nvim`?

**Comment by Anrock** [comment]
>actually libgit2_path = "libgit2" is already the default value.

My bad, I missed it.

>For require('fugit2.nvim').setup(...), where do you put it?

Just somewhere in init.lua after rock setup, yes.

>For versioning problem, as long as we don't specify pin=true, we can always update fugit2.nvim by :Rocks update command.

Ah, I stand corrected about being stuck in specific version then. However fugit won't be updated unless user explicitly executes `:Rocks update` after installing then, no?

>Do you think it will be better if I separate Rocks installation guide from lazy.nvim?

No strong opinion on this. I have a feeling that actually both guides can be in one page actually without it being too long if structured properly.

**Comment by SuperBo** [comment]
@Anrock, I updated this guide https://github.com/SuperBo/fugit2.nvim/wiki/%F0%9F%93%A6-Installation

the version is removed, plain lua config is provided beside rocks-config.nvim

**Comment by Anrock** [comment]
@SuperBo LGTM. I consider this issue resolved (w.r.t. my specific setup) unless @bitterjug has something else to add.

**Comment by SuperBo** [comment]
I will update README.md then close this issue later. @Anrock Thank you again for your contribution :D
