### ISSUE TITLE
bug: installation fails on Windows nvim. Using with AstroNvim.

### ISSUE THREAD

**Issue by saumyajyoti** [SuperBo/fugit2.nvim#82]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Win 11 23H2

### Describe the bug

Get build error as below:

fugit2.nvim 
        Installing https://luarocks.org/fugit2.nvim-0.2.0-1.src.rock
        Warning: Failed searching manifest: Failed downloading https://nvim-neorocks.github.io/rocks-binaries/dev/manifest-5.1 - failed downloading https://nvim-neorocks.github.io/rocks-binaries/dev/manifest-5.1

### Steps To Reproduce

1. Use with nvim via Lazy nvim
2. install spec:
https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/git/fugit2-nvim/init.lua

### Expected Behavior

The install and build should pass. Seeing this error recently, it used to work few weeks earlier.

**Comment by SuperBo** [comment]
@saumyajyoti, did AstroNvim use `rocks.nvim`, why it report error about rocks?

**Comment by saumyajyoti** [comment]
Hi @SuperBo , No it uses lazy.nvim.

**Comment by SuperBo** [comment]
are you using WSL or native windows shell?

**Comment by ZhichaoHong** [comment]
I got similar error. 
![image](https://github.com/user-attachments/assets/980b55c0-744f-4171-b634-6a202c8b57fa)

**Comment by SuperBo** [comment]
@ZhichaoHong, for temporarily fix, can you copy `libgit2.dll` of `libgit2.lib` to `C:\external\lib`?

**Comment by ZhichaoHong** [comment]
I copied the libgit2.dll in the c:\windows\system32. It still failed with the following error as below. It feels like the installation is trying to run git in a bash (basename, sed, etc) environment. But my default shell in neovim is still cmd.exe.
    ○ fugit2.nvim  Fugit2  Fugit2Graph 
        Warning: Failed searching manifest: Failed downloading https://nvim-neorocks.github.io/rocks-binaries/dev/manifest-5.1 - failed downloading https://nvim-neorocks.github.io/rocks-binaries/dev/manifest-5.1
        Cloning into 'nui.nvim'...
        C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
        C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
        C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found

        Error: Failed installing dependency: https://luarocks.org/dev/nui.nvim-dev-1.rockspec - Failed to fetch submodules.
        Installing https://luarocks.org/fugit2.nvim-0.2.1-1.src.rock
        Missing dependencies for fugit2.nvim 0.2.1-1:
           nui.nvim (not installed)
           nvim-web-devicons (not installed)
           plenary.nvim (not installed)

        fugit2.nvim 0.2.1-1 depends on lua >= 5.1 (5.1-1 provided by VM: success)
        fugit2.nvim 0.2.1-1 depends on nui.nvim (not installed)
        Installing https://luarocks.org/dev/nui.nvim-dev-1.rockspec
        Failed installing fugit2.nvim with `luarocks`.

        --------------------------------------------------------------------------------

        Trying to build from source.
        Cloning into 'nui.nvim'...
        C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
        C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
        C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found

        Error: Failed installing dependency: https://luarocks.org/dev/nui.nvim-dev-1.rockspec - Failed to fetch submodules.
        Missing dependencies for fugit2.nvim scm-1:
           nui.nvim (not installed)
           nvim-web-devicons (not installed)
           plenary.nvim (not installed)

**Comment by saumyajyoti** [comment]
@SuperBo , I am using Windows native shell. libgit2 is in path. The screenshot /error is same as @ZhichaoHong  mentioned above.

**Comment by mrcjkb** [comment]
This is because of lazy.nvim v11's addition of luarocks support.

There are two issues here: 

- lazy.nvim (afaik) has no way of telling luarocks where to find external libraries if they're not in the default search path. 
- It tries to install packages from the `dev` manifest, without trying to install from the root manifest first.
 This results in unstable versions of dependencies being installed, and in the case of nui.nvim it looks like it's trying and failing to check out a submodule (or its just Git for Windows that is broken here - in any case this would likely be solved by prioritising the root manifest).

A workaround could be to disable lazy.nvim's luarocks support by default: 

```lua
require('lazy').setup('my_plugins', { rocks = { enabled = false } })
```

**Comment by saumyajyoti** [comment]
Thanks @mrcjkb , I'll give it a try.

**Comment by saumyajyoti** [comment]
Issue resolved after I removed rockspec from the Lazy.nvim opts.

**Comment by mrcjkb** [comment]
This should hopefully solve the issue on the lazy.nvim side: https://github.com/folke/lazy.nvim/pull/1687
(apart from the ability to specify where to find libgit2).

**Comment by SuperBo** [comment]
Thank you @mrcjkb, you rocks. I didn't know that lazy.nvim now have support for lua rocks :(
