### ISSUE TITLE
bug: how to turn off Fugit2Blame?

### ISSUE THREAD

**Issue by Anrock** [SuperBo/fugit2.nvim#86]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

whatever

### Operating system/version

who cares

### Describe the bug

> Usage questions such as "How do I...?" belong in Discussions and will be closed.

But there are no "Discussions" in this repo? Sorry for trash bug report but there is no other way to get in contact and template asks too much of irrelevant info

### Steps To Reproduce

1. :Fugit2Blame

### Expected Behavior

have a way to turn it off but there is none or it's not documented anywhere

**Comment by SuperBo** [comment]
@Anrock: press `q` or `Esc` my friend :D

**Comment by Anrock** [comment]
Oh boy, `q` and `Esc` was very unexpected. `toggle` is a bit more expected but I didn't have any autocomplete for `:Fugit2Blame` for some reason.

Anyway, maybe enable "Discussions" to reduce "how do I" trash-issues?

**Comment by SuperBo** [comment]
@Anrock, discussion is here https://github.com/SuperBo/fugit2.nvim/discussions/87.

I didn't know about discussion T_T before.
