### ISSUE TITLE
feature: compact file tree view

### ISSUE THREAD

**Issue by EpiCanard** [SuperBo/fugit2.nvim#91]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Hello,

The folder architecture of java projects favors the creation of folders with only one folder inside.

Here is a typical example of file tree inside fugit2 with a java project :

- src
  - main
    - java
      - fr
        - epicanard
          - myproject
            - folderA
              - fileA.java
            - folderB
              - fileB.java
  - test

### Describe the solution you'd like

The idea behind this feature is to have a compact view where a folder with a single folder child can be compacted into one line.
Maybe you can add a feature toggle in the config to be able to choose between normal view and compact view ?

Example :
- src
  - **main/java/fr/epicanard/myproject**
    - folderA
      - fileA.java
    - folderB
      - fileV.java
  - test

### Describe alternatives you've considered

no other alternatives

**Comment by EpiCanard** [comment]
Hello @SuperBo,

It works wells when the preview is closed, I can stage / unstage a compact folder
But when the preview is open I have the error `[Fugit2] Failed to get unstage patch`  when I try to stage / unstage a folder

**Comment by SuperBo** [comment]
sorry @EpiCanard, https://github.com/SuperBo/fugit2.nvim/commit/00ab1fc7e77db15ce884dd195e876c0f7f759a37 this should fix that issue.

Could you help me verify this solve the new bug when patch view is on?

**Comment by EpiCanard** [comment]
Your fix works, I can stage / unstaged a folder with the preview open.

I can't discard a folder, but it doesn't seem to work with the commit before the compact folder feature.

**Comment by SuperBo** [comment]
Can you create new issue with the discard problem for directory @EpiCanard :D. That maybe not related to new compact view.

I will close this issue for better issue tracking. 
Thank you for your suggestion and testing new feature @EpiCanard .

**Comment by EpiCanard** [comment]
New issue created https://github.com/SuperBo/fugit2.nvim/issues/93

Thanks for adding this compact folder feature, it will be pleasant to use :)
