### ISSUE TITLE
bug: Discard a folder is not working

### ISSUE THREAD

**Issue by EpiCanard** [SuperBo/fugit2.nvim#93]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.11.0

### Operating system/version

Linux

### Describe the bug

Hello,

When I try to discard a folder, the confirmation popup is shown but nothing happen after I confirm.
It works file by file but not with a folder.

Thanks in advance for the fix

### Steps To Reproduce

1. Edit a file in a folder and save it
2. Open fugit2
3. Discard the parent folder
4. Select Yes in the popup

### Expected Behavior

The expected behavior is to discard all files contained in the selected folder

**Comment by SuperBo** [comment]
Hi @EpiCanard, please help me test latest changes, this PR https://github.com/SuperBo/fugit2.nvim/pull/94 should fix discard issue with directory.

**Comment by EpiCanard** [comment]
Hi @SuperBo, it works well :+1:
Thanks a lot for the fix !

**Comment by SuperBo** [comment]
@EpiCanard thank you for using Fugit2 :D
